# Generated by Django 3.0.2 on 2020-02-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrivalTime', models.DateTimeField()),
                ('numPassenger', models.IntegerField()),
                ('isShare', models.BooleanField()),
                ('isComfirmed', models.BooleanField()),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiderDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10)),
                ('vehicleType', models.CharField(max_length=20)),
                ('special', models.TextField(max_length=2000)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ride.RiderOwner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
