# Generated by Django 3.0.2 on 2020-02-03 04:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0002_mytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('arrivalTime', models.DateTimeField(default=datetime.datetime(2020, 2, 3, 4, 16, 1, 381480, tzinfo=utc))),
                ('numPassenger', models.IntegerField()),
                ('isShare', models.BooleanField()),
                ('isComfirmed', models.BooleanField()),
                ('special', models.TextField(max_length=1000)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rideOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='riderowner',
            name='caller',
        ),
        migrations.DeleteModel(
            name='RiderDriver',
        ),
        migrations.DeleteModel(
            name='RiderOwner',
        ),
    ]
