# Generated by Django 3.0.2 on 2020-02-03 04:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0003_auto_20200203_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 4, 19, 7, 845052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='caller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rideOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
