# Generated by Django 3.0.2 on 2020-02-03 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20200203_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrivalTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 4, 36, 15, 103661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='isComfirmed',
            field=models.BooleanField(null=True),
        ),
    ]
