# Generated by Django 3.0.2 on 2020-02-03 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0005_auto_20200203_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='arrivalTime',
        ),
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='isComfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('earliest', models.DateTimeField(default=datetime.datetime(2020, 2, 3, 18, 24, 45, 847177, tzinfo=utc))),
                ('latest', models.DateTimeField(default=datetime.datetime(2020, 2, 3, 18, 24, 45, 847200, tzinfo=utc))),
                ('numPassenger', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareOwner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
