# Generated by Django 3.0.2 on 2020-02-03 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_auto_20200203_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='earliest',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 18, 32, 39, 359298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='latest',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 3, 18, 32, 39, 359322, tzinfo=utc)),
        ),
    ]
