# Generated by Django 3.0.2 on 2020-02-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20200203_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharer',
            name='earliest',
        ),
        migrations.RemoveField(
            model_name='ridesharer',
            name='latest',
        ),
        migrations.AddField(
            model_name='ride',
            name='isDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='earliest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='earliest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='latest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='latest_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
