# Generated by Django 3.0.2 on 2020-02-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_auto_20200204_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='isDriver',
        ),
    ]
