# Generated by Django 3.0.2 on 2020-02-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_remove_ride_isdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicletype',
            field=models.CharField(choices=[('micro', 'micro'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('sedan', 'sedan'), ('CUV', 'CUV'), ('any', 'any')], default='any', max_length=6),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toshare', to='ride.Ride'),
        ),
    ]
