# Generated by Django 3.0.2 on 2020-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_auto_20200204_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrivalTime',
            field=models.DateTimeField(null=True),
        ),
    ]
