# Generated by Django 3.0.2 on 2020-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0011_auto_20200205_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharer',
            name='earliest_date',
        ),
        migrations.RemoveField(
            model_name='ridesharer',
            name='earliest_time',
        ),
        migrations.RemoveField(
            model_name='ridesharer',
            name='latest_date',
        ),
        migrations.RemoveField(
            model_name='ridesharer',
            name='latest_time',
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='earliest',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='latest',
            field=models.DateTimeField(null=True),
        ),
    ]
