# Generated by Django 3.0.2 on 2020-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_auto_20200205_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharer',
            name='isComfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
