# Generated by Django 3.0.2 on 2020-02-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_remove_ridesharer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='totalNum',
            field=models.IntegerField(null=True),
        ),
    ]
