# Generated by Django 3.0.2 on 2020-02-05 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0015_ride_totalnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicletype', models.CharField(choices=[('micro', 'micro'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('sedan', 'sedan'), ('CUV', 'CUV'), ('any', 'any')], default='any', max_length=6)),
                ('plate', models.CharField(max_length=10)),
                ('maxPassengers', models.IntegerField()),
                ('special', models.CharField(blank=True, max_length=1000, null=True)),
                ('duser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
