# Generated by Django 3.0.2 on 2020-02-05 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0016_ridedriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedriver',
            name='duser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
