# Generated by Django 3.0.2 on 2020-02-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0017_auto_20200205_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='ride.RideDriver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicletype',
            field=models.CharField(choices=[('micro', 'micro'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('sedan', 'sedan'), ('CUV', 'CUV')], default='sedan', max_length=6),
        ),
        migrations.AlterField(
            model_name='ridedriver',
            name='vehicletype',
            field=models.CharField(choices=[('micro', 'micro'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('sedan', 'sedan'), ('CUV', 'CUV')], default='sedan', max_length=6),
        ),
    ]
