# Generated by Django 3.0.2 on 2020-02-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0018_auto_20200206_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharer', to='ride.Ride'),
        ),
    ]
